# Generated by Django 6.1 on 2026-08-09 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='優惠碼')),
                ('discount_type', models.CharField(choices=[('fixed', '固定金額'), ('percentage', '百分比')], default='fixed', max_length=20, verbose_name='折扣類型')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='固定金額請填元數（例如 100）；百分比請填 0-100（例如 10 代表折 10%）', max_digits=10, verbose_name='折扣數值')),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消費金額')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='限首次購買')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效時間')),
                ('valid_until', models.DateTimeField(verbose_name='到期時間')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='留空代表不限制次數', null=True, verbose_name='使用次數上限')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '優惠券',
                'verbose_name_plural': '優惠券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('min_spend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='門檻金額')),
                ('reward_type', models.CharField(choices=[('discount', '折抵金額'), ('free_gift', '贈送商品')], default='discount', max_length=20, verbose_name='優惠類型')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='優惠類型為「折抵金額」時填寫', max_digits=10, null=True, verbose_name='折抵金額')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_gift_product', models.ForeignKey(blank=True, help_text='優惠類型為「贈送商品」時選擇，出貨時請記得附上贈品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_rules', to='products.product', verbose_name='贈品')),
            ],
            options={
                'verbose_name': '滿額活動',
                'verbose_name_plural': '滿額活動',
                'ordering': ['min_spend'],
            },
        ),
    ]
