# Generated by Django 6.1 on 2026-08-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('target_tier', models.CharField(blank=True, choices=[('bronze', '銅級會員'), ('silver', '銀級會員'), ('gold', '金級會員'), ('platinum', '白金會員')], help_text='留空代表發送給所有會員；有選的話只會發給該等級的會員', max_length=20, verbose_name='發送對象等級')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='發送時間')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='發送人數')),
            ],
            options={
                'verbose_name': '會員公告',
                'verbose_name_plural': '會員公告',
                'ordering': ['-created_at'],
            },
        ),
    ]
