# Generated by Django 6.1 on 2026-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_threshold', models.DecimalField(decimal_places=2, default=3000, help_text='累計已完成訂單金額達到此門檻自動升級為銀卡會員', max_digits=10, verbose_name='升級銀卡門檻')),
                ('gold_threshold', models.DecimalField(decimal_places=2, default=10000, help_text='累計已完成訂單金額達到此門檻自動升級為金卡會員', max_digits=10, verbose_name='升級金卡門檻')),
                ('points_earn_rate', models.DecimalField(decimal_places=2, default=1, help_text='訂單完成時依「實付金額 x 此比例」無條件捨去計算獲得點數', max_digits=6, verbose_name='消費 1 元可得點數')),
                ('points_redeem_rate', models.DecimalField(decimal_places=2, default=10, help_text='例如設 10，代表 10 點可折抵 NT$1（即 100 點折 NT$10）', max_digits=6, verbose_name='折抵 1 元所需點數')),
            ],
            options={
                'verbose_name': '會員等級與點數設定',
                'verbose_name_plural': '會員等級與點數設定',
            },
        ),
    ]
