"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 讀取 .env（本機開發用，正式環境改由 PaaS 平台的環境變數頁面設定，不需要這個檔案）
env = environ.Env(
    DEBUG=(bool, True),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 本機沒設 .env 時會用這組僅供開發用的預設值；正式環境務必在平台環境變數設定自己的 SECRET_KEY。
SECRET_KEY = env('SECRET_KEY', default='django-insecure-0$#5e^0q323270glyg%92+2p-292#2tqausaurlrihh1vo!vf*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'accounts',
    'products',
    'orders',
    'cart',
    'marketing',
]

SITE_ID = 1

AUTH_USER_MODEL = 'accounts.Member'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'products:product_list'
LOGOUT_REDIRECT_URL = 'products:product_list'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 第三方登入：目前只實際串接 Google（需在後台 Sites / Social applications 填入自己申請的
# Client ID / Secret 才能運作，見 SETUP.md）。Facebook / LINE 之後要加時，安裝對應的
# allauth provider app 並在 SOCIALACCOUNT_PROVIDERS 補上設定即可，架構不用再改。
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# 開發階段沒設資料庫 URL 時預設用 SQLite。正式環境（例如 Railway）可設定
# DATABASE_URL，或直接使用 Railway MySQL 服務提供的 MYSQL_URL。
database_url = env(
    'DATABASE_URL',
    default=env('MYSQL_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
)

DATABASES = {
    'default': env.db_url(database_url)
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# 商品圖片等使用者上傳的檔案（MEDIA）：多數 PaaS（含 Railway）的檔案系統是「無狀態」的，
# 每次重新部署都會清空，所以正式環境的商品圖片建議改存雲端物件儲存（例如 S3、Cloudflare R2），
# 這裡先維持本機檔案系統，開發階段沒問題，正式上線前記得處理。
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# 開發階段預設用 console backend，寄出的信會直接印在跑 runserver 的終端機視窗，不會真的寄出。
# 正式上線要接 SendGrid 等寄信服務時，設定環境變數：
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.sendgrid.net（依服務商提供的為準）
#   EMAIL_HOST_USER=...
#   EMAIL_HOST_PASSWORD=...
# 不需要改這裡的程式碼。

_EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

if _EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS = {
        'default': {
            'BACKEND': _EMAIL_BACKEND,
            'OPTIONS': {
                'host': env('EMAIL_HOST', default='localhost'),
                'port': env.int('EMAIL_PORT', default=587),
                'username': env('EMAIL_HOST_USER', default=''),
                'password': env('EMAIL_HOST_PASSWORD', default=''),
                'use_tls': env.bool('EMAIL_USE_TLS', default=True),
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': _EMAIL_BACKEND,
        },
    }

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')
