# Generated by Django 6.1 on 2026-08-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'ATM/銀行匯款'), ('cod', '貨到付款')], max_length=20, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('pending_payment', '待付款'), ('paid', '已付款'), ('preparing', '備貨中'), ('shipped', '已出貨'), ('completed', '已完成'), ('returning', '退貨中'), ('returned', '已退貨')], default='pending_payment', max_length=20, verbose_name='訂單狀態')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='收件人電話')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='收件地址')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='訂單總金額')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='託運單號')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='訂單')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant', verbose_name='商品規格')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
            },
        ),
    ]
