# Generated by Django 6.1 on 2026-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('home_delivery', '宅配到家'), ('convenience_store', '超商取貨')], default='home_delivery', max_length=20, verbose_name='物流方式'),
        ),
    ]
