# Generated by Django 6.1 on 2026-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='超商門市名稱'),
        ),
    ]
