# Generated by Django 6.1 on 2026-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='退貨原因'),
        ),
    ]
