# Generated by Django 6.1 on 2026-08-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('orders', '0004_order_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.coupon', verbose_name='使用的優惠券'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='優惠券折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_description',
            field=models.CharField(blank=True, help_text='出貨時記得附上此贈品', max_length=200, verbose_name='贈品'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='點數折抵金額'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='本單獲得點數'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.PositiveIntegerField(default=0, verbose_name='使用點數'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.promotionrule', verbose_name='套用的滿額活動'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='滿額折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小計'),
        ),
    ]
