# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_order_coupon_order_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='店到店運費'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10, verbose_name='店到店運費'),
        ),
    ]
