# Generated by Django 6.1 on 2026-08-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='網址代稱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='網址代稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', '均一尺寸')], max_length=10, verbose_name='尺寸')),
                ('color', models.CharField(max_length=50, verbose_name='顏色')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='貨號')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品規格',
                'verbose_name_plural': '商品規格',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
