# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.TextField(
                blank=True,
                help_text='每行輸入「尺寸代碼|對照文案」，例如 XS|32 / 70 A-B 杯。',
                verbose_name='尺寸對照',
            ),
        ),
    ]
