# Generated by Codex on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='jp_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='日文分類名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='jp_description',
            field=models.TextField(blank=True, verbose_name='日文商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='jp_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='日文商品名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='jp_size_guide',
            field=models.TextField(
                blank=True,
                help_text='每行輸入「尺寸代碼|日文對照文案」，例如 M|着丈 62cm / 身幅 48cm。',
                verbose_name='日文尺寸對照',
            ),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='jp_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='日文顏色'),
        ),
    ]
