# Generated by Codex on 2026-09-05

from django.db import migrations


def populate_japanese_product_names(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')

    category_names = {
        '套裝': 'セット',
        '內衣': 'インナー',
    }
    for zh_name, jp_name in category_names.items():
        Category.objects.filter(name=zh_name, jp_name='').update(jp_name=jp_name)

    product_names = {
        '純慾點點三件套➕飄帶': 'ドット柄3点セット（リボン付き）',
        '平口內衣': 'チューブトップブラ',
    }
    for zh_name, jp_name in product_names.items():
        Product.objects.filter(name=zh_name, jp_name='').update(jp_name=jp_name)

    color_names = {
        '固定': 'ワンカラー',
        '白色': 'ホワイト',
    }
    for zh_color, jp_color in color_names.items():
        ProductVariant.objects.filter(color=zh_color, jp_color='').update(jp_color=jp_color)


def clear_japanese_product_names(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')

    Category.objects.filter(name__in=['套裝', '內衣']).update(jp_name='')
    Product.objects.filter(name__in=['純慾點點三件套➕飄帶', '平口內衣']).update(jp_name='')
    ProductVariant.objects.filter(color__in=['固定', '白色']).update(jp_color='')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_japanese_product_fields'),
    ]

    operations = [
        migrations.RunPython(populate_japanese_product_names, clear_japanese_product_names),
    ]
