# Generated by Codex on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_populate_japanese_product_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qoo10_url',
            field=models.URLField(
                blank=True,
                help_text='完成 Qoo10 商品上架後，貼上該商品的完整網址；只會顯示在日本頁。',
                max_length=500,
                verbose_name='Qoo10 商品連結',
            ),
        ),
    ]
