# Generated by Codex on 2026-09-17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_qoo10_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='支援 MP4、WebM、OGG；建議使用 MP4（H.264）以獲得最佳相容性。', upload_to='products/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='商品影片')),
                ('poster', models.ImageField(blank=True, help_text='選填；未上傳時縮圖會顯示影片的第一個可載入畫面。', null=True, upload_to='products/video-posters/', verbose_name='影片封面')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='顯示順序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_videos', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品影片',
                'verbose_name_plural': '商品影片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
